version: "3.7"
services:
  web:
    restart: unless-stopped
    build: ./client
    ports:
      - "4173:4173"
    volumes:
      - ./config.json5:/usr/src/app/dist/config.json5
  ws:
    restart: unless-stopped
    build: ./server
    ports:
      - "5678:5678"
    environment:
      - WEB_TOKEN=secret
      - TURTLE_TOKEN=secret2
      - PORT=5678